# Global Energy & Climate Explorer

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/our-world-in-data-dataset-february-2026/owid-energy-data.csv
/kaggle/input/our-world-in-data-dataset-february-2026/owid-energy-codebook.csv

# Initial Data Inspection

In [2]:
df = pd.read_csv('/kaggle/input/our-world-in-data-dataset-february-2026/owid-energy-data.csv')
df.shape # IT HAS 23232 rows and 130 columns

(23232, 130)

In [3]:
list(df.columns)

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'biofuel_cons_change_pct',
 'biofuel_cons_change_twh',
 'biofuel_cons_per_capita',
 'biofuel_consumption',
 'biofuel_elec_per_capita',
 'biofuel_electricity',
 'biofuel_share_elec',
 'biofuel_share_energy',
 'carbon_intensity_elec',
 'coal_cons_change_pct',
 'coal_cons_change_twh',
 'coal_cons_per_capita',
 'coal_consumption',
 'coal_elec_per_capita',
 'coal_electricity',
 'coal_prod_change_pct',
 'coal_prod_change_twh',
 'coal_prod_per_capita',
 'coal_production',
 'coal_share_elec',
 'coal_share_energy',
 'electricity_demand',
 'electricity_demand_per_capita',
 'electricity_generation',
 'electricity_share_energy',
 'energy_cons_change_pct',
 'energy_cons_change_twh',
 'energy_per_capita',
 'energy_per_gdp',
 'fossil_cons_change_pct',
 'fossil_cons_change_twh',
 'fossil_elec_per_capita',
 'fossil_electricity',
 'fossil_energy_per_capita',
 'fossil_fuel_consumption',
 'fossil_share_elec',
 'fossil_share_energy',
 'gas_cons_change_pct',
 'gas_cons_change_twh',
 'gas_consumption',
 'gas_elec_per_capita',
 'gas_electricity',
 'gas_energy_per_capita',
 'gas_prod_change_pct',
 'gas_prod_change_twh',
 'gas_prod_per_capita',
 'gas_production',
 'gas_share_elec',
 'gas_share_energy',
 'greenhouse_gas_emissions',
 'hydro_cons_change_pct',
 'hydro_cons_change_twh',
 'hydro_consumption',
 'hydro_elec_per_capita',
 'hydro_electricity',
 'hydro_energy_per_capita',
 'hydro_share_elec',
 'hydro_share_energy',
 'low_carbon_cons_change_pct',
 'low_carbon_cons_change_twh',
 'low_carbon_consumption',
 'low_carbon_elec_per_capita',
 'low_carbon_electricity',
 'low_carbon_energy_per_capita',
 'low_carbon_share_elec',
 'low_carbon_share_energy',
 'net_elec_imports',
 'net_elec_imports_share_demand',
 'nuclear_cons_change_pct',
 'nuclear_cons_change_twh',
 'nuclear_consumption',
 'nuclear_elec_per_capita',
 'nuclear_electricity',
 'nuclear_energy_per_capita',
 'nuclear_share_elec',
 'nuclear_share_energy',
 'oil_cons_change_pct',
 'oil_cons_change_twh',
 'oil_consumption',
 'oil_elec_per_capita',
 'oil_electricity',
 'oil_energy_per_capita',
 'oil_prod_change_pct',
 'oil_prod_change_twh',
 'oil_prod_per_capita',
 'oil_production',
 'oil_share_elec',
 'oil_share_energy',
 'other_renewable_consumption',
 'other_renewable_electricity',
 'other_renewable_exc_biofuel_electricity',
 'other_renewables_cons_change_pct',
 'other_renewables_cons_change_twh',
 'other_renewables_elec_per_capita',
 'other_renewables_elec_per_capita_exc_biofuel',
 'other_renewables_energy_per_capita',
 'other_renewables_share_elec',
 'other_renewables_share_elec_exc_biofuel',
 'other_renewables_share_energy',
 'per_capita_electricity',
 'primary_energy_consumption',
 'renewables_cons_change_pct',
 'renewables_cons_change_twh',
 'renewables_consumption',
 'renewables_elec_per_capita',
 'renewables_electricity',
 'renewables_energy_per_capita',
 'renewables_share_elec',
 'renewables_share_energy',
 'solar_cons_change_pct',
 'solar_cons_change_twh',
 'solar_consumption',
 'solar_elec_per_capita',
 'solar_electricity',
 'solar_energy_per_capita',
 'solar_share_elec',
 'solar_share_energy',
 'wind_cons_change_pct',
 'wind_cons_change_twh',
 'wind_consumption',
 'wind_elec_per_capita',
 'wind_electricity',
 'wind_energy_per_capita',
 'wind_share_elec',
 'wind_share_energy']

In [4]:
df.tail()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
23227,Zimbabwe,2020,ZWE,15526887.0,2.317871e+10,NaN,0.0,0.0,0.0,6.440,0.10,1.490,NaN,371.09,NaN,NaN,NaN,NaN,176.468,2.74,3.004,0.592,1306.886,20.292,40.835,NaN,8.69,559.674,6.71,NaN,-15.539,-6.179,2163.068,1.449,NaN,NaN,179.044,2.78,NaN,NaN,41.431,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.49,NaN,NaN,NaN,245.381,3.81,NaN,56.781,NaN,NaN,NaN,NaN,253.109,3.93,NaN,58.569,NaN,1.98,22.785,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2.576,0.04,NaN,NaN,NaN,NaN,NaN,0.596,NaN,NaN,0.10,0.0,NaN,NaN,6.440,0.0,NaN,1.490,0.0,NaN,432.154,33.586,NaN,NaN,NaN,253.109,3.93,NaN,58.569,NaN,NaN,NaN,NaN,1.288,0.02,NaN,0.298,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23228,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,NaN,0.0,0.0,0.0,6.963,0.11,1.284,NaN,269.55,NaN,NaN,NaN,NaN,158.889,2.51,19.708,3.999,1537.673,24.291,29.288,NaN,10.31,652.646,8.57,NaN,12.059,4.050,2382.434,1.497,NaN,NaN,158.889,2.51,NaN,NaN,29.288,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.31,NaN,NaN,NaN,375.383,5.93,NaN,69.195,NaN,NaN,NaN,NaN,383.612,6.06,NaN,70.712,NaN,1.74,16.877,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.11,0.0,NaN,NaN,6.963,0.0,NaN,1.284,0.0,NaN,542.500,37.636,NaN,NaN,NaN,383.612,6.06,NaN,70.712,NaN,NaN,NaN,NaN,1.266,0.02,NaN,0.233,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23229,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,NaN,0.0,0.0,0.0,6.845,0.11,1.230,NaN,297.54,NaN,NaN,NaN,NaN,181.716,2.92,21.665,5.263,1839.164,29.554,32.662,NaN,10.85,675.211,8.94,NaN,55.118,20.744,3633.067,2.254,NaN,NaN,181.716,2.92,NaN,NaN,32.662,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.66,NaN,NaN,NaN,365.921,5.88,NaN,65.772,NaN,NaN,NaN,NaN,374.633,6.02,NaN,67.338,NaN,1.91,17.604,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.11,0.0,NaN,NaN,6.845,0.0,NaN,1.230,0.0,NaN,556.349,58.380,NaN,NaN,NaN,374.633,6.02,NaN,67.338,NaN,NaN,NaN,NaN,1.867,0.03,NaN,0.336,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23230,Zimbabwe,2023,ZWE,16340829.0,NaN,NaN,0.0,0.0,0.0,7.344,0.12,1.444,NaN,298.44,NaN,NaN,NaN,NaN,165.230,2.70,26.593,7.859,2289.525,37.413,32.491,NaN,10.21,624.815,8.31,NaN,-10.952,-6.394,3181.361,NaN,NaN,NaN,165.230,2.70,NaN,NaN,32.491,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.48,NaN,NaN,NaN,334.132,5.46,NaN,65.704,NaN,NaN,NaN,NaN,343.312,5.61,NaN,67.509,NaN,1.90,18.609,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.12,0.0,NaN,NaN,7.344,0.0,NaN,1.444,0.0,NaN,508.542,51.986,NaN,NaN,NaN,343.312,5.61,NaN,67.509,NaN,NaN,NaN,NaN,1.836,0.03,NaN,0.361,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23231,Zimbabwe,2024,ZWE,16634366.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.205,6.063,2613.587,43.475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dict(df[df['country'] == 'Philippines'].isnull().sum())

{'country': np.int64(0),
 'year': np.int64(0),
 'iso_code': np.int64(0),
 'population': np.int64(0),
 'gdp': np.int64(9),
 'biofuel_cons_change_pct': np.int64(105),
 'biofuel_cons_change_twh': np.int64(66),
 'biofuel_cons_per_capita': np.int64(65),
 'biofuel_consumption': np.int64(65),
 'biofuel_elec_per_capita': np.int64(100),
 'biofuel_electricity': np.int64(100),
 'biofuel_share_elec': np.int64(100),
 'biofuel_share_energy': np.int64(65),
 'carbon_intensity_elec': np.int64(100),
 'coal_cons_change_pct': np.int64(66),
 'coal_cons_change_twh': np.int64(66),
 'coal_cons_per_capita': np.int64(65),
 'coal_consumption': np.int64(65),
 'coal_elec_per_capita': np.int64(100),
 'coal_electricity': np.int64(100),
 'coal_prod_change_pct': np.int64(21),
 'coal_prod_change_twh': np.int64(9),
 'coal_prod_per_capita': np.int64(8),
 'coal_production': np.int64(8),
 'coal_share_elec': np.int64(100),
 'coal_share_energy': np.int64(65),
 'electricity_demand': np.int64(100),
 'electricity_demand_per_capita': np.int64(100),
 'electricity_generation': np.int64(85),
 'electricity_share_energy': np.int64(85),
 'energy_cons_change_pct': np.int64(66),
 'energy_cons_change_twh': np.int64(66),
 'energy_per_capita': np.int64(65),
 'energy_per_gdp': np.int64(67),
 'fossil_cons_change_pct': np.int64(66),
 'fossil_cons_change_twh': np.int64(66),
 'fossil_elec_per_capita': np.int64(100),
 'fossil_electricity': np.int64(100),
 'fossil_energy_per_capita': np.int64(65),
 'fossil_fuel_consumption': np.int64(65),
 'fossil_share_elec': np.int64(100),
 'fossil_share_energy': np.int64(65),
 'gas_cons_change_pct': np.int64(95),
 'gas_cons_change_twh': np.int64(66),
 'gas_consumption': np.int64(65),
 'gas_elec_per_capita': np.int64(100),
 'gas_electricity': np.int64(100),
 'gas_energy_per_capita': np.int64(65),
 'gas_prod_change_pct': np.int64(104),
 'gas_prod_change_twh': np.int64(89),
 'gas_prod_per_capita': np.int64(88),
 'gas_production': np.int64(88),
 'gas_share_elec': np.int64(100),
 'gas_share_energy': np.int64(65),
 'greenhouse_gas_emissions': np.int64(100),
 'hydro_cons_change_pct': np.int64(66),
 'hydro_cons_change_twh': np.int64(66),
 'hydro_consumption': np.int64(65),
 'hydro_elec_per_capita': np.int64(65),
 'hydro_electricity': np.int64(65),
 'hydro_energy_per_capita': np.int64(65),
 'hydro_share_elec': np.int64(85),
 'hydro_share_energy': np.int64(65),
 'low_carbon_cons_change_pct': np.int64(66),
 'low_carbon_cons_change_twh': np.int64(66),
 'low_carbon_consumption': np.int64(65),
 'low_carbon_elec_per_capita': np.int64(65),
 'low_carbon_electricity': np.int64(65),
 'low_carbon_energy_per_capita': np.int64(65),
 'low_carbon_share_elec': np.int64(85),
 'low_carbon_share_energy': np.int64(65),
 'net_elec_imports': np.int64(100),
 'net_elec_imports_share_demand': np.int64(100),
 'nuclear_cons_change_pct': np.int64(125),
 'nuclear_cons_change_twh': np.int64(66),
 'nuclear_consumption': np.int64(65),
 'nuclear_elec_per_capita': np.int64(65),
 'nuclear_electricity': np.int64(65),
 'nuclear_energy_per_capita': np.int64(65),
 'nuclear_share_elec': np.int64(85),
 'nuclear_share_energy': np.int64(65),
 'oil_cons_change_pct': np.int64(66),
 'oil_cons_change_twh': np.int64(66),
 'oil_consumption': np.int64(65),
 'oil_elec_per_capita': np.int64(100),
 'oil_electricity': np.int64(100),
 'oil_energy_per_capita': np.int64(65),
 'oil_prod_change_pct': np.int64(89),
 'oil_prod_change_twh': np.int64(9),
 'oil_prod_per_capita': np.int64(8),
 'oil_production': np.int64(8),
 'oil_share_elec': np.int64(100),
 'oil_share_energy': np.int64(65),
 'other_renewable_consumption': np.int64(65),
 'other_renewable_electricity': np.int64(65),
 'other_renewable_exc_biofuel_electricity': np.int64(100),
 'other_renewables_cons_change_pct': np.int64(78),
 'other_renewables_cons_change_twh': np.int64(66),
 'other_renewables_elec_per_capita': np.int64(65),
 'other_renewables_elec_per_capita_exc_biofuel': np.int64(100),
 'other_renewables_energy_per_capita': np.int64(65),
 'other_renewables_share_elec': np.int64(85),
 'other_renewables_share_elec_exc_biofuel': np.int64(100),
 'other_renewables_share_energy': np.int64(65),
 'per_capita_electricity': np.int64(85),
 'primary_energy_consumption': np.int64(65),
 'renewables_cons_change_pct': np.int64(66),
 'renewables_cons_change_twh': np.int64(66),
 'renewables_consumption': np.int64(65),
 'renewables_elec_per_capita': np.int64(65),
 'renewables_electricity': np.int64(65),
 'renewables_energy_per_capita': np.int64(65),
 'renewables_share_elec': np.int64(85),
 'renewables_share_energy': np.int64(65),
 'solar_cons_change_pct': np.int64(106),
 'solar_cons_change_twh': np.int64(66),
 'solar_consumption': np.int64(65),
 'solar_elec_per_capita': np.int64(65),
 'solar_electricity': np.int64(65),
 'solar_energy_per_capita': np.int64(65),
 'solar_share_elec': np.int64(85),
 'solar_share_energy': np.int64(65),
 'wind_cons_change_pct': np.int64(106),
 'wind_cons_change_twh': np.int64(66),
 'wind_consumption': np.int64(65),
 'wind_elec_per_capita': np.int64(65),
 'wind_electricity': np.int64(65),
 'wind_energy_per_capita': np.int64(65),
 'wind_share_elec': np.int64(85),
 'wind_share_energy': np.int64(65)}

In [6]:
philippines = df[df['country']=='Philippines']
philippines

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
17257,Philippines,1900,PHL,6644021.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17258,Philippines,1901,PHL,6739540.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17259,Philippines,1902,PHL,6845501.0,8.164457e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17260,Philippines,1903,PHL,6962152.0,9.941910e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17261,Philippines,1904,PHL,7080757.0,8.552128e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17377,Philippines,2020,PHL,112081270.0,8.922563e+11,-15.286,-0.934,46.168,5.175,11.153,1.25,1.229,0.998,598.82,0.369,0.751,1820.662,204.062,519.088,58.18,NaN,NaN,NaN,NaN,57.179,39.344,101.75,907.823,101.75,21.246,-9.249,-52.363,4583.800,0.576,-10.008,-50.280,715.106,80.15,4034.009,452.137,78.771,87.173,-8.851,-3.732,38.428,173.981,19.50,342.861,NaN,NaN,NaN,NaN,19.165,7.409,60.93,-10.004,-2.036,17.874,64.150,7.19,159.473,7.066,3.446,-4.758,-1.813,66.528,192.717,21.60,593.568,21.229,12.827,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-18.408,-47.299,209.646,22.038,2.47,1870.486,NaN,NaN,NaN,NaN,2.428,40.420,37.556,12.01,10.76,2.444,0.896,107.154,96.002,335.076,11.803,10.575,7.241,907.823,513.758,-4.758,-1.813,66.528,192.717,21.60,593.568,21.229,12.827,10.154,0.305,3.389,12.223,1.37,30.239,1.346,0.653,-1.460,-0.044,2.534,9.190,1.03,22.613,1.012,0.489
17378,Philippines,2021,PHL,113100947.0,9.431417e+11,12.133,0.628,51.303,5.802,12.820,1.45,1.371,1.055,599.62,7.792,15.901,1944.839,219.963,548.625,62.05,NaN,NaN,NaN,NaN,58.676,40.010,105.75,935.005,105.75,20.826,6.190,31.799,4823.633,0.578,5.850,26.448,728.111,82.35,4231.482,478.585,77.872,87.052,-14.565,-5.597,32.831,165.162,18.68,290.283,NaN,NaN,NaN,NaN,17.664,5.972,63.41,27.561,4.870,22.744,81.255,9.19,201.095,8.690,4.137,9.079,4.655,71.183,206.895,23.40,629.372,22.128,12.948,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.700,16.144,225.790,14.323,1.62,1996.360,NaN,NaN,NaN,NaN,1.532,41.070,35.818,11.47,10.02,-4.626,-1.737,101.414,88.593,316.694,10.846,9.475,6.515,935.005,545.557,9.079,4.655,71.183,206.895,23.40,629.372,22.128,12.948,7.497,0.245,3.634,12.997,1.47,32.133,1.390,0.661,25.919,0.649,3.183,11.229,1.27,28.147,1.201,0.579
17379,Philippines,2022,PHL,113964343.0,1.014811e+12,8.891,0.516,55.440,6.318,11.583,1.32,1.184,1.098,602.67,0.856,1.883,1946.624,221.846,582.902,66.43,NaN,NaN,NaN,NaN,59.568,38.553,111.52,978.552,111.52,20.984,4.660,25.422,5010.157,0.563,4.568,21.859,761.905,86.83,4391.233,500.444,77.860,86.968,-6.176,-2.028,30.804,156.891,17.88,270.293,NaN,NaN,NaN,NaN,16.033,5.353,67.21,9.681,2.141,24.885,88.536,10.09,218.354,9.048,4.324,6.177,3.807,74.990,216.647,24.69,658.013,22.140,13.032,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.745,22.004,247.794,22.112,2.52,2174.315,NaN,NaN,NaN,NaN,2.260,43.062,36.708,11.75,10.43,2.485,0.890,103.102,91.520,322.103,10.536,9.353,6.379,978.552,570.979,6.177,3.807,74.990,216.647,24.69,658.013,22.140,13.032,23.912,0.858,4.492,15.970,1.82,39.418,1.632,0.781,-18.549,-0.597,2.587,9.038,1.03,22.697,0.924,0.450
17380,Philippines,2023,PHL,114891199.0,NaN,5.087,0.321,57.790,6.640,10.271,1.18,1.011,1.083,612.54,11.624,25.788,2155.379,247.634,634.600,72.91,NaN,NaN,NaN,NaN,62.444,40.383,116.76,1016.266,116.76,20.621,6.619,37.792,5298.678,NaN,6.699,33.525,793.272,91.14,4647.606,533.969,78.058,87.078,4.004,1.233,32.037,140.046,16.09,278.849,NaN,NaN,NaN,NaN,13.780,5.225,71.52,2.009,0.314,25.199,87.822,10.09,219.327,8.642,4.109,6.168,4.248,79.238,222.994,25.62,689.676,21.942,12.922,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.624,6.503,254.298,18.626,2.14,2213.379,NaN,NaN,NaN,NaN,1.833,41.470,37.935,11.79,10.61,3.341,1.226,102.619,92.348,330.178,10.098,9.087,6.186,1016.266,608.771,6.168,4.248,79.238,222.994,25.62,689.676,21.942,12.922,39.502,1.729,6.221,21.499,2.47,54.147,2.115,1.014,26.333,0.657,3.244,11.054,1.27,28.234,1.088,0.529
17381,Philippines,2024,PHL,115843663.0,NaN,4.714,0.313,60.017,6.953,11.136,1.29,1.025,1.059,612.35,9.556,23.665,2341.938,271.299,679.191,78.68,NaN,NaN,NaN,NaN,62.514,41.313,125.86,1086.464,125.86,20.741,7.193,43.791,5633.132,NaN,7.219,38.546,850.370,98.51,4942.136,572.515,78.270,87.182,4.977,1.594,33.632,153.224,17.75,290.320,NaN,NaN,NaN,NaN,14.103,5.121,77.07,7.638,1.925,27.123,93.833,10.87,234.138,8.637,4.130,6.765,4.940,84.178,236.094,27.35,726.649,21.730,12.818,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.225,13.287,267.585,17.955,2.08,2309.878,NaN,NaN,NaN,NaN,1.653,40.747,37.691,11.57,10.28,-0.641,-0.243,99.876,88.740,325.363,9.193,8.168,5.740,1086.464,652.563,6.765,4.940,84.178,236.094,27.35,726.649,21.730,12.818,48.604,3.024,9.245,31.767,3.68,79.803,2.924,1.408,-2.404,-0.078,3.166,10.618,1.23,27.329,0.977,0.482

In [7]:
year = df.groupby('year').size()
dict(year)

{1900: np.int64(118),
 1901: np.int64(118),
 1902: np.int64(118),
 1903: np.int64(118),
 1904: np.int64(118),
 1905: np.int64(118),
 1906: np.int64(118),
 1907: np.int64(118),
 1908: np.int64(118),
 1909: np.int64(118),
 1910: np.int64(118),
 1911: np.int64(118),
 1912: np.int64(118),
 1913: np.int64(118),
 1914: np.int64(118),
 1915: np.int64(118),
 1916: np.int64(118),
 1917: np.int64(118),
 1918: np.int64(118),
 1919: np.int64(118),
 1920: np.int64(118),
 1921: np.int64(118),
 1922: np.int64(118),
 1923: np.int64(118),
 1924: np.int64(118),
 1925: np.int64(118),
 1926: np.int64(118),
 1927: np.int64(118),
 1928: np.int64(118),
 1929: np.int64(118),
 1930: np.int64(118),
 1931: np.int64(118),
 1932: np.int64(118),
 1933: np.int64(118),
 1934: np.int64(118),
 1935: np.int64(118),
 1936: np.int64(118),
 1937: np.int64(118),
 1938: np.int64(118),
 1939: np.int64(118),
 1940: np.int64(118),
 1941: np.int64(118),
 1942: np.int64(118),
 1943: np.int64(118),
 1944: np.int64(118),
 1945: np.int64(118),
 1946: np.int64(118),
 1947: np.int64(118),
 1948: np.int64(118),
 1949: np.int64(118),
 1950: np.int64(118),
 1951: np.int64(118),
 1952: np.int64(118),
 1953: np.int64(118),
 1954: np.int64(118),
 1955: np.int64(118),
 1956: np.int64(118),
 1957: np.int64(118),
 1958: np.int64(118),
 1959: np.int64(118),
 1960: np.int64(118),
 1961: np.int64(118),
 1962: np.int64(118),
 1963: np.int64(118),
 1964: np.int64(118),
 1965: np.int64(159),
 1966: np.int64(159),
 1967: np.int64(159),
 1968: np.int64(159),
 1969: np.int64(159),
 1970: np.int64(159),
 1971: np.int64(159),
 1972: np.int64(159),
 1973: np.int64(159),
 1974: np.int64(159),
 1975: np.int64(159),
 1976: np.int64(160),
 1977: np.int64(160),
 1978: np.int64(160),
 1979: np.int64(160),
 1980: np.int64(270),
 1981: np.int64(271),
 1982: np.int64(271),
 1983: np.int64(271),
 1984: np.int64(271),
 1985: np.int64(281),
 1986: np.int64(282),
 1987: np.int64(282),
 1988: np.int64(282),
 1989: np.int64(282),
 1990: np.int64(289),
 1991: np.int64(287),
 1992: np.int64(292),
 1993: np.int64(291),
 1994: np.int64(292),
 1995: np.int64(293),
 1996: np.int64(293),
 1997: np.int64(294),
 1998: np.int64(294),
 1999: np.int64(294),
 2000: np.int64(306),
 2001: np.int64(306),
 2002: np.int64(306),
 2003: np.int64(307),
 2004: np.int64(307),
 2005: np.int64(308),
 2006: np.int64(307),
 2007: np.int64(307),
 2008: np.int64(307),
 2009: np.int64(307),
 2010: np.int64(307),
 2011: np.int64(307),
 2012: np.int64(308),
 2013: np.int64(308),
 2014: np.int64(308),
 2015: np.int64(308),
 2016: np.int64(308),
 2017: np.int64(294),
 2018: np.int64(294),
 2019: np.int64(294),
 2020: np.int64(293),
 2021: np.int64(293),
 2022: np.int64(293),
 2023: np.int64(293),
 2024: np.int64(178),
 2025: np.int64(37)}

In [8]:
unique_countries = df['country'].nunique()
unique_countries

314

In [9]:
# FINDING
sea_countries = ['Philippines', 'Indonesia', 'Vietnam', 
                 'Thailand', 'Myanmar', 'East Timor', 
                 'Malaysia', 'Singapore', 'Cambodia',
                'Laos', 'Brunei']
sea_df = df[df['country'].isin(sea_countries)]
sea_df

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
3140,Brunei,1900,BRN,16978.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3141,Brunei,1901,BRN,17540.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3142,Brunei,1902,BRN,18120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3143,Brunei,1903,BRN,18719.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3144,Brunei,1904,BRN,19338.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22475,Vietnam,2020,VNM,98079196.0,7.526296e+11,NaN,0.0,0.0,0.0,3.467,0.34,0.139,0.0,528.44,5.008,29.077,6216.825,609.741,1249.297,122.53,-3.856,-11.649,2961.505,290.462,50.217,50.168,245.51,2503.181,244.00,22.377,1.701,20.555,12527.920,1.633,-1.251,-12.733,1621.649,159.05,10251.231,1005.433,65.184,82.724,-10.196,-10.036,88.394,353.388,34.66,901.251,-10.196,-10.036,901.251,88.394,14.205,7.273,128.94,10.209,16.263,179.919,742.971,72.87,1834.421,29.865,14.803,17.971,31.509,209.976,866.137,84.95,2140.883,34.816,17.276,1.51,0.615,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-9.371,-31.774,307.297,18.964,1.86,3133.156,-12.395,-16.495,1188.610,116.578,0.762,25.283,1.062,0.34,NaN,-2.857,-0.031,3.467,NaN,10.833,0.139,NaN,0.087,2487.785,1228.728,17.971,31.509,209.976,866.137,84.95,2140.883,34.816,17.276,123.350,14.645,26.570,109.707,10.76,270.907,4.410,2.186,35.635,0.633,2.425,9.992,0.98,24.722,0.402,0.199
22476,Vietnam,2021,VNM,98935101.0,7.719120e+11,NaN,0.0,0.0,0.0,3.234,0.32,0.126,0.0,475.06,-5.003,-30.508,5854.675,579.233,1193.004,118.03,8.335,24.210,3180.588,314.672,46.540,48.000,254.43,2571.686,253.61,24.204,-0.435,-5.343,12365.529,1.585,-6.574,-66.102,1466.921,145.13,9494.412,939.331,57.226,77.840,-18.559,-16.405,71.989,265.932,26.31,727.639,-18.559,-16.405,727.639,71.989,10.374,5.966,120.48,7.968,13.857,193.776,795.168,78.67,1958.616,31.020,16.058,27.705,57.440,267.416,1096.476,108.48,2702.946,42.774,22.160,0.82,0.322,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.244,-19.189,288.109,7.985,0.79,2912.099,-5.624,-6.556,1112.064,110.022,0.312,23.875,1.000,0.32,NaN,-5.882,-0.062,3.234,NaN,10.108,0.126,NaN,0.083,2563.398,1223.385,27.705,57.440,267.416,1096.476,108.48,2702.946,42.774,22.160,143.016,37.841,64.411,264.315,26.15,651.046,10.311,5.338,240.224,5.804,8.229,33.760,3.34,83.176,1.317,0.682
22477,Vietnam,2022,VNM,99680656.0,8.338039e+11,NaN,0.0,0.0,0.0,3.812,0.38,0.143,0.0,415.41,-7.414,-42.942,5380.087,536.291,1043.733,104.04,3.186,10.024,3257.360,324.696,39.244,42.100,267.43,2682.867,265.11,24.490,5.731,70.110,12976.387,1.551,1.285,12.072,1344.092,133.98,9544.505,951.403,50.538,74.688,8.311,5.983,77.972,293.136,29.22,782.218,8.311,5.983,782.218,77.972,11.022,6.121,110.13,21.910,41.875,235.651,962.173,95.91,2364.061,36.177,18.499,20.873,55.021,322.437,1315.501,131.13,3234.698,49.462,25.312,2.32,0.868,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.018,49.031,337.140,7.223,0.72,3382.200,-1.271,-1.398,1089.722,108.624,0.272,26.466,1.181,0.38,NaN,18.125,0.181,3.812,NaN,11.850,0.143,NaN,0.093,2659.593,1293.495,20.873,55.021,322.437,1315.501,131.13,3234.698,49.462,25.312,-1.533,-1.144,63.268,258.325,25.75,634.705,9.713,4.967,172.104,14.108,22.337,91.191,9.09,224.082,3.429,1.753
22478,Vietnam,2023,VNM,100352189.0,NaN,NaN,0.0,0.0,0.0,8.669,0.87,0.315,0.0,472.40,17.978,96.416,6304.862,632.707,1293.046,129.76,-5.207,-16.907,3067.082,307.788,46.914,46.619,278.76,2777.817,276.59,23.328,6.374,82.441,13711.071,NaN,12.140,115.501,1572.661,157.82,10631.591,1066.903,57.059,78.612,-7.586,-5.915,72.057,262.675,26.36,718.041,-7.586,-5.915,718.041,72.057,9.530,5.309,130.66,-15.941,-39.015,196.637,803.371,80.62,1959.465,29.148,14.489,-9.427,-32.166,290.271,1183.532,118.77,2892.523,42.941,21.388,2.17,0.778,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.415,25.000,362.140,16.940,1.70,3608.687,-3.183,-3.457,1047.979,105.167,0.615,26.683,2.712,0.87,NaN,129.630,1.531,8.669,NaN,27.030,0.315,NaN,0.200,2756.193,1375.936,-9.427,-32.166,290.271,1183.532,118.77,2892.523,42.941,21.388,-0.225,-0.604,62.663,255.998,25.69,624.435,9.288,4.617,27.445,5.922,28.259,115.493,11.59,281.594,4.190,2.082
22479,Vietnam,2024,VNM,100987685.0,NaN,NaN,0.0,0.0,0.0,10.199,1.03,0.339,0.0,484.32,9.598,60.728,6866.531,693.435,1512.759,152.77,-7.258,-22.340,2826.571,285.449,50.323,47.587,305.75,3027.597,303.58,23.871,7.291,100.316,14618.140,NaN,7.169,76.486,1735.063,175.22,11322.070,1143.390,57.718,78.466,-15.362,-11.069,60.988,216.165,21.83,603.911,-15.362,-11.069,603.911,60.988,7.191,4.185,147.03,10.049,19.761,216.398,878.523,88.72,2142.812,29.225,14.850,8.081,23.520,313.791,1271.046,128.36,3107.219,42.282,21.534,2.17,0.710,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.408,26.827,388.967,6.139,0.62,3851.628,-5.958,-6.266,979.337,98.901,0.204,26.693,3.225,1.03,NaN,18.894,0.513,10.199,NaN,31.935,0.339,NaN,0.221,3006.109,1476.252,8.081,23.520,313.791,1271.046,128.36,3107.219,42.282,21.534,0.662,0.415,63.078,256.071,25.86,624.611,8.518,4.329,10.021,2.832,31.090,126.253,12.75,307.862,4.200,2.134

In [10]:
null_sea = sea_df.isnull().groupby(sea_df['country']).sum()
null_sea

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Brunei,0,0,0,0,125,125,66,65,65,101,101,101,125,101,125,125,125,125,101,101,125,89,88,88,101,125,101,101,101,125,82,82,81,125,125,125,101,101,125,125,101,125,125,125,125,101,101,125,48,1,0,0,101,125,101,125,125,125,101,101,125,101,125,125,125,125,101,101,125,101,125,101,101,125,66,65,65,65,65,101,125,125,125,125,101,101,125,32,1,0,0,101,125,125,101,101,125,125,101,101,125,101,101,125,101,81,125,125,125,101,101,125,101,125,125,125,125,101,101,125,101,125,125,125,125,101,101,125,101,125
Cambodia,0,0,0,0,2,45,45,45,45,20,20,20,45,20,45,45,45,45,20,20,45,9,8,8,20,45,20,20,20,45,2,2,1,2,45,45,20,20,45,45,20,45,45,45,45,20,20,45,45,9,8,8,20,45,20,45,45,45,20,20,45,20,45,45,45,45,20,20,45,20,45,20,20,45,45,45,20,20,45,20,45,45,45,45,20,20,45,45,9,8,8,20,45,45,20,20,45,45,20,20,45,20,20,45,20,1,45,45,45,20,20,45,20,45,45,45,45,20,20,45,20,45,45,45,45,20,20,45,20,45
East Timor,0,0,0,0,21,21,21,21,21,0,0,0,21,0,21,21,21,21,0,0,21,8,7,7,0,21,0,0,0,21,1,1,0,21,21,21,0,0,21,21,0,21,21,21,21,0,0,21,11,8,7,7,0,21,0,21,21,21,0,0,21,0,21,21,21,21,0,0,21,0,21,0,0,21,21,21,0,0,21,0,21,21,21,21,0,0,21,9,8,7,7,0,21,21,0,0,21,21,0,0,21,0,0,21,0,0,21,21,21,0,0,21,0,21,21,21,21,0,0,21,0,21,21,21,21,0,0,21,0,21
Indonesia,0,0,0,0,9,106,66,65,65,100,100,100,65,100,66,66,65,65,85,85,5,1,0,0,85,65,100,100,85,85,66,66,65,67,66,66,85,85,65,65,85,65,66,66,65,85,85,65,32,1,0,0,85,65,100,66,66,65,65,65,65,85,65,66,66,65,65,65,65,85,65,100,100,125,66,65,65,65,65,85,65,66,66,65,85,85,65,1,1,0,0,85,65,65,65,100,91,66,65,100,65,85,100,65,85,65,66,66,65,65,65,65,85,65,109,66,65,65,65,65,85,65,110,66,65,65,65,65,85,65
Laos,0,0,0,0,1,44,44,44,44,20,20,20,44,20,44,44,44,44,20,20,8,8,7,7,20,44,20,20,20,44,1,1,0,1,44,44,20,20,44,44,20,44,44,44,44,20,20,44,44,8,7,7,20,44,20,44,44,44,20,20,44,20,44,44,44,44,20,20,44,20,44,20,20,44,44,44,20,20,44,20,44,44,44,44,20,20,44,44,8,7,7,20,44,44,20,20,44,44,20,20,44,20,20,44,20,0,44,44,44,20,20,44,20,44,44,44,44,20,20,44,20,44,44,44,44,20,20,44,20,44
Malaysia,0,0,0,0,6,108,66,65,65,100,100,100,65,100,66,66,65,65,85,85,37,9,8,8,85,65,100,100,85,85,66,66,65,67,66,66,85,85,65,65,85,65,71,66,65,85,85,65,72,1,0,0,85,65,100,66,66,65,65,65,65,85,65,66,66,65,65,65,65,85,65,100,100,125,66,65,65,65,65,85,65,66,66,65,85,85,65,18,1,0,0,85,65,65,65,125,101,66,65,125,65,85,125,65,85,65,66,66,65,65,65,65,85,65,113,66,65,65,65,65,85,65,125,66,65,65,65,65,85,65
Myanmar,0,0,0,0,42,125,71,70,70,100,100,100,125,100,125,125,125,125,100,100,64,9,8,8,100,125,100,100,100,125,82,82,81,82,125,125,100,100,125,125,100,125,125,125,125,100,100,125,51,1,0,0,100,125,100,125,125,125,100,100,125,100,125,125,125,125,100,100,125,100,125,100,100,125,71,70,70,70,70,100,125,125,125,125,100,100,125,37,9,8,8,100,125,125,100,100,125,125,100,100,125,100,100,125,100,81,125,125,125,100,100,125,100,125,125,125,125,100,100,125,100,125,125,125,125,100,100,125,100,125
Philippines,0,0,0,0,9,105,66,65,65,100,100,100,65,100,66,66,65,65,100,100,21,9,8,8,100,65,100,100,85,85,66,66,65,67,66,66,100,100,65,65,100,65,95,66,65,100,100,65,104,89,88,88,100,65,100,66,66,65,65,65,65,85,65,66,66,65,65,65,65,85,65,100,100,125,66,65,65,65,65,85,65,66,66,65,100,100,65,89,9,8,8,100,65,65,65,100,78,66,65,100,65,85,100,65,85,65,66,66,65,65,65,65,85,65,106,66,65,65,65,65,85,65,106,66,65,65,65,65,85,65
Singapore,0,0,0,0,2,60,1,0,0,35,35,35,0,35,6,1,0,0,35,35,60,24,23,23,35,0,35,35,20,20,1,1,0,2,1,1,35,35,0,0,35,0,28,1,0,35,35,0,60,24,23,23,35,0,35,60,1,0,25,25,0,45,0,22,1,0,0,0,0,20,0,35,35,60,1,0,0,0,0,20,0,1,1,0,35,35,0,60,24,23,23,35,0,0,0,60,22,1,0,60,0,20,60,0,20,0,22,1,0,0,0,0,20,0,44,1,0,0,0,0,20,0,60,1,0,25,25,0,45,0
Thailand,0,0,0,0,49,104,66,65,65,100,100,100,65,100,66,66,65,65,85,85,53,1,0,0,85,65,100,100,85,85,66,66,65,67,66,66,85,85,65,65,85,65,82,66,65,85,85,65,82,1,0,0,85,65,100,66,66,65,65,65,65,85,65,66,66,65,65,65,65,85,65,100,100,125,66,65,65,65,65,85,65,66,66,65,85,85,65,77,1,0,0,85,65,65,65,125,88,66,65,125,65,85,125,65,85,65,66,66,65,65,65,65,85,65,107,66,65,65,65,65,85,65,107,66,65,65,65,65,85,65
Vietnam,0,0,0,0,51,125,66,65,65,100,100,100,65,100,66,66,65,65,85,85,1,1,0,0,85,65,100,100,85,85,66,66,65,67,66,66,85,85,65,65,85,65,82,66,65,85,85,65,82,71,70,70,85,65,100,66,66,65,65,65,65,85,65,66,66,65,65,65,65,85,65,100,100,125,66,65,65,65,65,85,65,66,66,65,85,85,65,88,66,65,65,85,65,65,65,125,106,66,65,125,65,85,125,65,85,65,66,66,65,65,65,65,85,65,111,66,65,65,65,65,85,65,109,66,65,65,65,65,85,65

In [11]:
rows_sea = sea_df[sea_df['year'] >= 2004].groupby('country')['year'].size()
rows_sea

country
Brunei         21
Cambodia       21
East Timor     20
Indonesia      21
Laos           20
Malaysia       21
Myanmar        21
Philippines    21
Singapore      21
Thailand       21
Vietnam        21
Name: year, dtype: int64

In [12]:
sea_df = sea_df[sea_df['year'] >= 2005]
sea_df.shape

(218, 130)

In [13]:
dict(sea_df.isnull().sum())

{'country': np.int64(0),
 'year': np.int64(0),
 'iso_code': np.int64(0),
 'population': np.int64(0),
 'gdp': np.int64(56),
 'biofuel_cons_change_pct': np.int64(142),
 'biofuel_cons_change_twh': np.int64(58),
 'biofuel_cons_per_capita': np.int64(58),
 'biofuel_consumption': np.int64(58),
 'biofuel_elec_per_capita': np.int64(1),
 'biofuel_electricity': np.int64(1),
 'biofuel_share_elec': np.int64(1),
 'biofuel_share_energy': np.int64(98),
 'carbon_intensity_elec': np.int64(1),
 'coal_cons_change_pct': np.int64(98),
 'coal_cons_change_twh': np.int64(98),
 'coal_cons_per_capita': np.int64(98),
 'coal_consumption': np.int64(98),
 'coal_elec_per_capita': np.int64(1),
 'coal_electricity': np.int64(1),
 'coal_prod_change_pct': np.int64(110),
 'coal_prod_change_twh': np.int64(62),
 'coal_prod_per_capita': np.int64(62),
 'coal_production': np.int64(62),
 'coal_share_elec': np.int64(1),
 'coal_share_energy': np.int64(98),
 'electricity_demand': np.int64(1),
 'electricity_demand_per_capita': np.int64(1),
 'electricity_generation': np.int64(1),
 'electricity_share_energy': np.int64(98),
 'energy_cons_change_pct': np.int64(3),
 'energy_cons_change_twh': np.int64(3),
 'energy_per_capita': np.int64(3),
 'energy_per_gdp': np.int64(56),
 'fossil_cons_change_pct': np.int64(98),
 'fossil_cons_change_twh': np.int64(98),
 'fossil_elec_per_capita': np.int64(1),
 'fossil_electricity': np.int64(1),
 'fossil_energy_per_capita': np.int64(98),
 'fossil_fuel_consumption': np.int64(98),
 'fossil_share_elec': np.int64(1),
 'fossil_share_energy': np.int64(98),
 'gas_cons_change_pct': np.int64(98),
 'gas_cons_change_twh': np.int64(98),
 'gas_consumption': np.int64(98),
 'gas_elec_per_capita': np.int64(1),
 'gas_electricity': np.int64(1),
 'gas_energy_per_capita': np.int64(98),
 'gas_prod_change_pct': np.int64(76),
 'gas_prod_change_twh': np.int64(38),
 'gas_prod_per_capita': np.int64(38),
 'gas_production': np.int64(38),
 'gas_share_elec': np.int64(1),
 'gas_share_energy': np.int64(98),
 'greenhouse_gas_emissions': np.int64(1),
 'hydro_cons_change_pct': np.int64(118),
 'hydro_cons_change_twh': np.int64(98),
 'hydro_consumption': np.int64(98),
 'hydro_elec_per_capita': np.int64(21),
 'hydro_electricity': np.int64(21),
 'hydro_energy_per_capita': np.int64(98),
 'hydro_share_elec': np.int64(21),
 'hydro_share_energy': np.int64(98),
 'low_carbon_cons_change_pct': np.int64(98),
 'low_carbon_cons_change_twh': np.int64(98),
 'low_carbon_consumption': np.int64(98),
 'low_carbon_elec_per_capita': np.int64(1),
 'low_carbon_electricity': np.int64(1),
 'low_carbon_energy_per_capita': np.int64(98),
 'low_carbon_share_elec': np.int64(1),
 'low_carbon_share_energy': np.int64(98),
 'net_elec_imports': np.int64(1),
 'net_elec_imports_share_demand': np.int64(1),
 'nuclear_cons_change_pct': np.int64(218),
 'nuclear_cons_change_twh': np.int64(58),
 'nuclear_consumption': np.int64(58),
 'nuclear_elec_per_capita': np.int64(0),
 'nuclear_electricity': np.int64(0),
 'nuclear_energy_per_capita': np.int64(58),
 'nuclear_share_elec': np.int64(1),
 'nuclear_share_energy': np.int64(98),
 'oil_cons_change_pct': np.int64(98),
 'oil_cons_change_twh': np.int64(98),
 'oil_consumption': np.int64(98),
 'oil_elec_per_capita': np.int64(1),
 'oil_electricity': np.int64(1),
 'oil_energy_per_capita': np.int64(98),
 'oil_prod_change_pct': np.int64(82),
 'oil_prod_change_twh': np.int64(46),
 'oil_prod_per_capita': np.int64(46),
 'oil_production': np.int64(46),
 'oil_share_elec': np.int64(1),
 'oil_share_energy': np.int64(98),
 'other_renewable_consumption': np.int64(98),
 'other_renewable_electricity': np.int64(1),
 'other_renewable_exc_biofuel_electricity': np.int64(81),
 'other_renewables_cons_change_pct': np.int64(99),
 'other_renewables_cons_change_twh': np.int64(98),
 'other_renewables_elec_per_capita': np.int64(1),
 'other_renewables_elec_per_capita_exc_biofuel': np.int64(81),
 'other_renewables_energy_per_capita': np.int64(98),
 'other_renewables_share_elec': np.int64(1),
 'other_renewables_share_elec_exc_biofuel': np.int64(81),
 'other_renewables_share_energy': np.int64(98),
 'per_capita_electricity': np.int64(1),
 'primary_energy_consumption': np.int64(3),
 'renewables_cons_change_pct': np.int64(98),
 'renewables_cons_change_twh': np.int64(98),
 'renewables_consumption': np.int64(98),
 'renewables_elec_per_capita': np.int64(1),
 'renewables_electricity': np.int64(1),
 'renewables_energy_per_capita': np.int64(98),
 'renewables_share_elec': np.int64(1),
 'renewables_share_energy': np.int64(98),
 'solar_cons_change_pct': np.int64(123),
 'solar_cons_change_twh': np.int64(98),
 'solar_consumption': np.int64(98),
 'solar_elec_per_capita': np.int64(1),
 'solar_electricity': np.int64(1),
 'solar_energy_per_capita': np.int64(98),
 'solar_share_elec': np.int64(1),
 'solar_share_energy': np.int64(98),
 'wind_cons_change_pct': np.int64(150),
 'wind_cons_change_twh': np.int64(98),
 'wind_consumption': np.int64(98),
 'wind_elec_per_capita': np.int64(21),
 'wind_electricity': np.int64(21),
 'wind_energy_per_capita': np.int64(98),
 'wind_share_elec': np.int64(21),
 'wind_share_energy': np.int64(98)}

In [14]:
null_sea = sea_df.isnull().groupby(sea_df['country']).sum()
null_sea

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Brunei,0,0,0,0,20,20,0,0,0,1,1,1,20,1,20,20,20,20,1,1,20,8,8,8,1,20,1,1,1,20,1,1,1,20,20,20,1,1,20,20,1,20,20,20,20,1,1,20,0,0,0,0,1,20,1,20,20,20,1,1,20,1,20,20,20,20,1,1,20,1,20,1,1,20,0,0,0,0,0,1,20,20,20,20,1,1,20,0,0,0,0,1,20,20,1,1,20,20,1,1,20,1,1,20,1,1,20,20,20,1,1,20,1,20,20,20,20,1,1,20,1,20,20,20,20,1,1,20,1,20
Cambodia,0,0,0,0,2,20,20,20,20,0,0,0,20,0,20,20,20,20,0,0,20,8,8,8,0,20,0,0,0,20,1,1,1,2,20,20,0,0,20,20,0,20,20,20,20,0,0,20,20,8,8,8,0,20,0,20,20,20,0,0,20,0,20,20,20,20,0,0,20,0,20,0,0,20,20,20,0,0,20,0,20,20,20,20,0,0,20,20,8,8,8,0,20,20,0,0,20,20,0,0,20,0,0,20,0,1,20,20,20,0,0,20,0,20,20,20,20,0,0,20,0,20,20,20,20,0,0,20,0,20
East Timor,0,0,0,0,19,19,19,19,19,0,0,0,19,0,19,19,19,19,0,0,19,7,7,7,0,19,0,0,0,19,0,0,0,19,19,19,0,0,19,19,0,19,19,19,19,0,0,19,9,7,7,7,0,19,0,19,19,19,0,0,19,0,19,19,19,19,0,0,19,0,19,0,0,19,19,19,0,0,19,0,19,19,19,19,0,0,19,7,7,7,7,0,19,19,0,0,19,19,0,0,19,0,0,19,0,0,19,19,19,0,0,19,0,19,19,19,19,0,0,19,0,19,19,19,19,0,0,19,0,19
Indonesia,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0
Laos,0,0,0,0,1,19,19,19,19,0,0,0,19,0,19,19,19,19,0,0,7,7,7,7,0,19,0,0,0,19,0,0,0,1,19,19,0,0,19,19,0,19,19,19,19,0,0,19,19,7,7,7,0,19,0,19,19,19,0,0,19,0,19,19,19,19,0,0,19,0,19,0,0,19,19,19,0,0,19,0,19,19,19,19,0,0,19,19,7,7,7,0,19,19,0,0,19,19,0,0,19,0,0,19,0,0,19,19,19,0,0,19,0,19,19,19,19,0,0,19,0,19,19,19,19,0,0,19,0,19
Malaysia,0,0,0,0,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,8,8,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,20,0,0,20,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0
Myanmar,0,0,0,0,2,20,0,0,0,0,0,0,20,0,20,20,20,20,0,0,8,8,8,8,0,20,0,0,0,20,1,1,1,2,20,20,0,0,20,20,0,20,20,20,20,0,0,20,0,0,0,0,0,20,0,20,20,20,0,0,20,0,20,20,20,20,0,0,20,0,20,0,0,20,0,0,0,0,0,0,20,20,20,20,0,0,20,8,8,8,8,0,20,20,0,0,20,20,0,0,20,0,0,20,0,1,20,20,20,0,0,20,0,20,20,20,20,0,0,20,0,20,20,20,20,0,0,20,0,20
Philippines,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,8,8,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,8,8,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
Singapore,0,0,0,0,2,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,8,8,8,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,8,8,8,0,0,0,20,0,0,20,20,0,20,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,20,8,8,8,0,0,0,0,20,0,0,0,20,0,0,20,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,20,0,0,20,20,0,20,0
Thailand,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,20,0,0,20,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
Vietnam,0,0,0,0,2,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,1,0,0,20,0,0,20,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0

In [15]:
selected_columns = [
    'country', 'year', 'iso_code',
    'population', 'gdp',
    'fossil_share_energy',
    'renewables_share_energy',
    'solar_share_energy',
    'wind_share_energy',
    'hydro_share_energy',
    'low_carbon_share_energy',
    'primary_energy_consumption',
    'fossil_fuel_consumption',
    'renewables_consumption',
    'energy_per_capita',
    'renewables_cons_change_pct',
    'fossil_cons_change_pct',
    'greenhouse_gas_emissions',
    'carbon_intensity_elec',
    'energy_per_gdp'
]

f_sea_df = sea_df[selected_columns].copy()
f_sea_df.shape

(218, 20)

In [16]:
nulls = f_sea_df.isnull().groupby(sea_df['country']).sum()
nulls

,country,year,iso_code,population,gdp,fossil_share_energy,renewables_share_energy,solar_share_energy,wind_share_energy,hydro_share_energy,low_carbon_share_energy,primary_energy_consumption,fossil_fuel_consumption,renewables_consumption,energy_per_capita,renewables_cons_change_pct,fossil_cons_change_pct,greenhouse_gas_emissions,carbon_intensity_elec,energy_per_gdp
country,,,,,,,,,,,,,,,,,,,,
Brunei,0,0,0,0,20,20,20,20,20,20,20,1,20,20,1,20,20,1,1,20
Cambodia,0,0,0,0,2,20,20,20,20,20,20,1,20,20,1,20,20,0,0,2
East Timor,0,0,0,0,19,19,19,19,19,19,19,0,19,19,0,19,19,0,0,19
Indonesia,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Laos,0,0,0,0,1,19,19,19,19,19,19,0,19,19,0,19,19,0,0,1
Malaysia,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Myanmar,0,0,0,0,2,20,20,20,20,20,20,1,20,20,1,20,20,0,0,2
Philippines,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Singapore,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Thailand,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Vietnam,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2

In [17]:
# FINDING
top_sea = ['Philippines', 'Indonesia', 'Vietnam', 
                 'Thailand', 
                 'Malaysia', 'Singapore']
sea_six_df = f_sea_df[f_sea_df['country'].isin(top_sea)]
sea_six_df

,country,year,iso_code,population,gdp,fossil_share_energy,renewables_share_energy,solar_share_energy,wind_share_energy,hydro_share_energy,low_carbon_share_energy,primary_energy_consumption,fossil_fuel_consumption,renewables_consumption,energy_per_capita,renewables_cons_change_pct,fossil_cons_change_pct,greenhouse_gas_emissions,carbon_intensity_elec,energy_per_gdp
9739,Indonesia,2005,IDN,230871648.0,1.474875e+12,96.506,3.494,0.000,0.000,2.034,3.494,1416.892,1367.980,49.523,6137.142,6.250,2.824,86.45,650.54,0.961
9740,Indonesia,2006,IDN,233951650.0,1.565013e+12,96.766,3.234,0.000,0.000,1.784,3.234,1441.128,1395.470,46.632,6159.938,-5.862,2.010,92.20,668.12,0.921
9741,Indonesia,2007,IDN,237062338.0,1.674227e+12,96.626,3.374,0.000,0.000,1.939,3.374,1546.681,1495.455,52.218,6524.362,13.382,7.165,98.41,663.14,0.924
9742,Indonesia,2008,IDN,240157902.0,1.809491e+12,96.380,3.620,0.000,0.000,1.942,3.620,1564.584,1509.474,56.691,6514.816,8.398,0.937,101.80,652.98,0.865
9743,Indonesia,2009,IDN,243220024.0,1.905717e+12,96.264,3.736,0.000,0.001,1.856,3.736,1607.271,1549.363,60.130,6608.300,8.580,2.643,107.60,660.65,0.843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22475,Vietnam,2020,VNM,98079196.0,7.526296e+11,82.724,17.276,2.186,0.199,14.803,17.276,1228.728,1005.433,209.976,12527.920,17.971,-1.251,128.94,528.44,1.633
22476,Vietnam,2021,VNM,98935101.0,7.719120e+11,77.840,22.160,5.338,0.682,16.058,22.160,1223.385,939.331,267.416,12365.529,27.705,-6.574,120.48,475.06,1.585
22477,Vietnam,2022,VNM,99680656.0,8.338039e+11,74.688,25.312,4.967,1.753,18.499,25.312,1293.495,951.403,322.437,12976.387,20.873,1.285,110.13,415.41,1.551
22478,Vietnam,2023,VNM,100352189.0,NaN,78.612,21.388,4.617,2.082,14.489,21.388,1375.936,1066.903,290.271,13711.071,-9.427,12.140,130.66,472.40,NaN
22479,Vietnam,2024,VNM,100987685.0,NaN,78.466,21.534,4.329,2.134,14.850,21.534,1476.252,1143.390,313.791,14618.140,8.081,7.169,147.03,484.32,NaN

In [18]:
sea_six_df.isnull().groupby(sea_df['country']).sum()

,country,year,iso_code,population,gdp,fossil_share_energy,renewables_share_energy,solar_share_energy,wind_share_energy,hydro_share_energy,low_carbon_share_energy,primary_energy_consumption,fossil_fuel_consumption,renewables_consumption,energy_per_capita,renewables_cons_change_pct,fossil_cons_change_pct,greenhouse_gas_emissions,carbon_intensity_elec,energy_per_gdp
country,,,,,,,,,,,,,,,,,,,,
Indonesia,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Malaysia,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Philippines,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Singapore,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Thailand,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
Vietnam,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2

In [19]:
# Year-over-Year (YoY) change

sea_six_df['yoy_rse'] = sea_six_df.sort_values('year').groupby('country')['renewables_share_energy'].pct_change() * 100
sea_six_df['yoy_fse'] = sea_six_df.sort_values('year').groupby('country')['fossil_share_energy'].pct_change() * 100

/tmp/ipykernel_17/4082330482.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sea_six_df['yoy_rse'] = sea_six_df.sort_values('year').groupby('country')['renewables_share_energy'].pct_change() * 100
/tmp/ipykernel_17/4082330482.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sea_six_df['yoy_fse'] = sea_six_df.sort_values('year').groupby('country')['fossil_share_energy'].pct_change() * 100

In [20]:
# Cumulative Change Since Baseline
sea_six_df = sea_six_df.sort_values('year')

sea_six_df['cum_rse'] = sea_six_df.groupby('country')['renewables_share_energy'].transform(lambda x: (x - x.iloc[0]) / x.iloc[0] * 100)
sea_six_df['cum_fse'] = sea_six_df.groupby('country')['fossil_share_energy'].transform(lambda x: (x - x.iloc[0]) / x.iloc[0] * 100)

In [21]:
sea_six_df.tail(20)

,country,year,iso_code,population,gdp,fossil_share_energy,renewables_share_energy,solar_share_energy,wind_share_energy,hydro_share_energy,low_carbon_share_energy,primary_energy_consumption,fossil_fuel_consumption,renewables_consumption,energy_per_capita,renewables_cons_change_pct,fossil_cons_change_pct,greenhouse_gas_emissions,carbon_intensity_elec,energy_per_gdp,yoy_rse,yoy_fse,cum_rse,cum_fse
18759,Singapore,2021,SGP,5546291.0,4.455520e+11,99.662,0.338,0.107,0.000,0.000,0.338,912.046,908.861,3.080,164442.578,9.140,-0.170,28.24,506.18,2.047,7.643312,-0.024076,22.909091,-0.063174
20546,Thailand,2021,THA,71727338.0,1.095187e+12,92.966,7.034,0.888,0.629,0.808,7.034,1386.818,1286.562,97.350,19334.578,-2.550,0.447,99.83,566.06,1.266,0.918221,-0.068795,233.681214,-5.032076
20547,Thailand,2022,THA,71735321.0,1.124144e+12,92.752,7.248,0.892,0.530,1.171,7.248,1387.880,1284.390,100.366,19347.238,-0.272,-0.169,101.06,560.29,1.235,3.042366,-0.230192,243.833017,-5.250684
11966,Malaysia,2022,MYS,34695494.0,8.775842e+11,92.167,7.833,0.508,0.000,5.957,7.833,1355.509,1244.331,105.746,39068.727,15.421,8.121,110.92,604.04,1.545,2.445723,-0.202482,263.480278,-5.803056
9756,Indonesia,2022,IDN,278830527.0,3.500094e+12,89.792,10.208,0.040,0.032,2.435,10.208,2749.242,2472.905,281.127,9859.904,13.991,26.317,225.41,675.81,0.785,-7.836764,0.976114,192.157985,-6.957080
22477,Vietnam,2022,VNM,99680656.0,8.338039e+11,74.688,25.312,4.967,1.753,18.499,25.312,1293.495,951.403,322.437,12976.387,20.873,1.285,110.13,415.41,1.551,14.223827,-4.049332,108.192137,-14.974614
17379,Philippines,2022,PHL,113964343.0,1.014811e+12,86.968,13.032,0.781,0.450,4.324,13.032,570.979,500.444,74.990,5010.157,6.177,4.568,67.21,602.67,0.563,0.648749,-0.096494,-21.743830,4.344488
18760,Singapore,2022,SGP,5649888.0,4.618011e+11,99.479,0.521,0.183,0.000,0.000,0.521,895.630,890.796,4.668,158521.719,53.019,-1.988,28.70,504.22,1.939,54.142012,-0.183621,89.454545,-0.246678
9757,Indonesia,2023,IDN,281190068.0,NaN,89.305,10.695,0.062,0.042,2.149,10.695,2785.135,2491.822,298.421,9904.812,10.337,0.765,238.69,680.80,NaN,4.770768,-0.542365,206.096165,-7.461712
17380,Philippines,2023,PHL,114891199.0,NaN,87.078,12.922,1.014,0.529,4.109,12.922,608.771,533.969,79.238,5298.678,6.168,6.699,71.52,612.54,NaN,-0.844076,0.126483,-22.404372,4.476466
22478,Vietnam,2023,VNM,100352189.0,NaN,78.612,21.388,4.617,2.082,14.489,21.388,1375.936,1066.903,290.271,13711.071,-9.427,12.140,130.66,472.40,NaN,-15.502528,5.253856,75.917092,-10.507502
11967,Malaysia,2023,MYS,35126295.0,NaN,91.883,8.117,0.606,0.000,5.998,8.117,1325.126,1212.272,107.088,37724.605,3.328,-2.576,114.16,607.88,NaN,3.625686,-0.308136,276.658933,-6.093311
20548,Thailand,2023,THA,71702436.0,NaN,92.392,7.608,0.905,0.659,1.160,7.608,1388.184,1279.415,105.355,19360.342,6.286,-0.387,104.62,549.24,NaN,4.966887,-0.388132,260.910816,-5.618437
18761,Singapore,2023,SGP,5789092.0,NaN,99.507,0.493,0.229,0.000,0.000,0.493,991.330,986.239,4.887,171241.078,8.065,10.714,28.71,500.87,NaN,-5.374280,0.028147,79.272727,-0.218601
9758,Indonesia,2024,IDN,283487933.0,NaN,89.046,10.954,0.075,0.039,2.160,10.954,2984.731,2663.047,327.601,10528.601,8.690,6.871,252.74,680.25,NaN,2.421692,-0.290017,213.508872,-7.730089
11968,Malaysia,2024,MYS,35557670.0,NaN,91.718,8.282,0.624,0.000,6.094,8.282,1381.980,1262.247,113.976,38865.867,7.110,4.122,119.81,604.43,NaN,2.032771,-0.179576,284.315545,-6.261945
17381,Philippines,2024,PHL,115843663.0,NaN,87.182,12.818,1.408,0.482,4.130,12.818,652.563,572.515,84.178,5633.132,6.765,7.219,77.07,612.35,NaN,-0.804829,0.119433,-23.028884,4.601245
18762,Singapore,2024,SGP,5832387.0,NaN,99.455,0.545,0.295,0.000,0.000,0.545,1053.921,1047.929,5.745,180701.453,19.774,6.255,29.73,498.74,NaN,10.547667,-0.052258,98.181818,-0.270745
20549,Thailand,2024,THA,71668010.0,NaN,92.597,7.403,0.935,0.582,1.104,7.403,1420.819,1312.641,104.940,19825.014,-0.549,2.597,110.68,554.73,NaN,-2.694532,0.221881,251.185958,-5.409022
22479,Vietnam,2024,VNM,100987685.0,NaN,78.466,21.534,4.329,2.134,14.850,21.534,1476.252,1143.390,313.791,14618.140,8.081,7.169,147.03,484.32,NaN,0.682626,-0.185722,77.117947,-10.673710